openapi: 3.0.1
info:
  title: Agent-Based RAG Service API
  description: API for interacting with the AI agent that performs retrieval-augmented generation using OpenAI Agents SDK and existing retrieval pipeline
  version: 1.0.0
servers:
  - url: http://localhost:8001
    description: Development server
  - url: https://api.physicalairobotics.com
    description: Production server

paths:
  /api/agent/query:
    post:
      summary: Submit a query to the AI agent for processing
      description: Processes a natural language query using the AI agent with retrieval-augmented generation capabilities
      operationId: processAgentQuery
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AgentQueryRequest'
      responses:
        '200':
          description: Successfully processed query and returned agent response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgentQueryResponse'
        '400':
          description: Invalid query parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: Rate limit exceeded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      tags:
        - Agent
      security:
        - bearerAuth: []

  /api/agent/validate-response:
    post:
      summary: Validate that an agent response is properly grounded
      description: Validates that an agent response is properly grounded in retrieved content and meets quality standards
      operationId: validateAgentResponse
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ValidationRequest'
      responses:
        '200':
          description: Validation completed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationResponse'
        '400':
          description: Invalid validation parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      tags:
        - Validation
      security:
        - bearerAuth: []

  /api/agent/session/{session_id}:
    get:
      summary: Get session details
      description: Retrieves details about a specific agent session
      operationId: getSessionDetails
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier for the session
      responses:
        '200':
          description: Session details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionDetailsResponse'
        '404':
          description: Session not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      tags:
        - Session Management
      security:
        - bearerAuth: []

    delete:
      summary: Terminate a session
      description: Ends a specific agent session and cleans up resources
      operationId: terminateSession
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier for the session
      responses:
        '200':
          description: Session terminated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionTerminationResponse'
        '404':
          description: Session not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      tags:
        - Session Management
      security:
        - bearerAuth: []

  /api/agent/health:
    get:
      summary: Health check for the agent service
      description: Returns the health status of the agent service and its dependencies
      operationId: healthCheck
      responses:
        '200':
          description: Health check completed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheckResponse'
        '503':
          description: Service is unhealthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheckResponse'
      tags:
        - Health
      security: []

tags:
  - name: Agent
    description: Agent query and response operations
  - name: Validation
    description: Response validation and quality checking
  - name: Session Management
    description: Session lifecycle management
  - name: Health
    description: Health and status checks

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    AgentQueryRequest:
      type: object
      required:
        - query
      properties:
        query:
          type: string
          description: Natural language query text
          example: "Explain digital twin simulation concepts"
          minLength: 1
          maxLength: 500
        session_id:
          type: string
          description: Unique session identifier (optional, new session created if not provided)
          example: "sess_abc123xyz"
          pattern: "^[a-zA-Z0-9_-]+$"
        top_k:
          type: integer
          description: Number of results to retrieve (default: 5)
          minimum: 1
          maximum: 20
          default: 5
          example: 5
        min_relevance:
          type: number
          description: Minimum relevance threshold (default: 0.3)
          minimum: 0.0
          maximum: 1.0
          default: 0.3
          example: 0.3
        query_types:
          type: array
          description: Types of queries to prioritize (optional)
          items:
            type: string
            enum: [conceptual, factual, section-based]
          example: ["conceptual"]

    AgentQueryResponse:
      type: object
      required:
        - response
        - source_attributions
        - processing_time
        - session_id
        - timestamp
      properties:
        response:
          type: string
          description: Generated response based on retrieved context
          example: "Digital twin simulation is a virtual representation of a physical system that enables real-time monitoring, analysis, and optimization of the physical counterpart. It uses sensors and data to mirror the real-world behavior of the system..."
        source_attributions:
          type: array
          description: Sources used in the response with attribution
          items:
            $ref: '#/components/schemas/SourceAttribution'
        confidence_score:
          type: number
          description: Agent's confidence in the response (0.0-1.0)
          minimum: 0.0
          maximum: 1.0
          example: 0.85
        processing_time:
          type: number
          description: Time taken to process the query in seconds
          example: 2.34
        session_id:
          type: string
          description: Session identifier for the interaction
          example: "sess_abc123xyz"
        timestamp:
          type: string
          description: ISO 8601 timestamp of the response
          format: date-time
          example: "2025-12-21T01:00:00Z"
        intermediate_steps:
          type: array
          description: Steps taken by the agent during processing
          items:
            type: object
            description: A step in the agent's processing
            example: {"step": "retrieve_context", "description": "Retrieved 5 relevant chunks from knowledge base"}

    SourceAttribution:
      type: object
      required:
        - source_url
        - section_title
        - chunk_index
        - relevance_score
      properties:
        source_url:
          type: string
          description: URL of the source document
          format: uri
          example: "https://physicalairobotics.netlify.app/docs/module-2-digital-twin-simulation/chapter-1-introduction"
        section_title:
          type: string
          description: Title of the section containing the information
          example: "Introduction to Digital Twin Simulation"
        chunk_index:
          type: integer
          description: Index of the chunk in the original document
          example: 2
        relevance_score:
          type: number
          description: Relevance of this source to the query (0.0-1.0)
          minimum: 0.0
          maximum: 1.0
          example: 0.85
        extracted_text:
          type: string
          description: The actual text that was used from the source
          example: "Digital twin simulation is a virtual representation of a physical system..."

    ValidationRequest:
      type: object
      required:
        - query
        - response
        - retrieved_context
      properties:
        query:
          type: string
          description: Original query text
          example: "What is digital twin simulation?"
          minLength: 1
          maxLength: 500
        response:
          type: string
          description: Agent response to validate
          example: "Digital twin simulation is a virtual representation of a physical system..."
          minLength: 1
          maxLength: 2000
        retrieved_context:
          type: array
          description: Context used by the agent for the response
          items:
            $ref: '#/components/schemas/ValidationContextChunk'
        expected_sources:
          type: array
          description: Expected source URLs that should be used (optional)
          items:
            type: string
            format: uri
          example: ["https://physicalairobotics.netlify.app/docs/module-2/"]

    ValidationContextChunk:
      type: object
      required:
        - content
        - source_url
        - relevance_score
      properties:
        content:
          type: string
          description: The content chunk text
          example: "Digital twin simulation is a virtual representation of a physical system..."
        source_url:
          type: string
          description: URL of the source document
          format: uri
          example: "https://physicalairobotics.netlify.app/docs/module-2-digital-twin-simulation/"
        relevance_score:
          type: number
          description: Relevance score of the chunk (0.0-1.0)
          minimum: 0.0
          maximum: 1.0
          example: 0.85

    ValidationResponse:
      type: object
      required:
        - is_properly_grounded
        - grounding_percentage
        - validation_time
      properties:
        is_properly_grounded:
          type: boolean
          description: Whether the response is properly grounded in retrieved content
          example: true
        grounding_percentage:
          type: number
          description: Percentage of response grounded in context (0.0-1.0)
          minimum: 0.0
          maximum: 1.0
          example: 0.85
        validation_notes:
          type: string
          description: Additional notes about the validation
          example: "Response appropriately uses retrieved content with good attribution"
        validation_time:
          type: number
          description: Time taken for validation in seconds
          example: 0.12

    SessionDetailsResponse:
      type: object
      required:
        - session_id
        - created_at
        - last_interaction
        - active
        - conversation_history
      properties:
        session_id:
          type: string
          description: Unique identifier for the session
          example: "sess_abc123xyz"
        created_at:
          type: string
          description: ISO 8601 timestamp when session was created
          format: date-time
          example: "2025-12-21T00:00:00Z"
        last_interaction:
          type: string
          description: ISO 8601 timestamp of last interaction
          format: date-time
          example: "2025-12-21T01:00:00Z"
        active:
          type: boolean
          description: Whether the session is still active
          example: true
        conversation_history:
          type: array
          description: History of the conversation in this session
          items:
            $ref: '#/components/schemas/ConversationTurn'

    ConversationTurn:
      type: object
      required:
        - turn_id
        - query
        - response
        - timestamp
      properties:
        turn_id:
          type: string
          description: Unique identifier for this turn
          example: "turn_def456uvw"
        query:
          type: string
          description: The user's query in this turn
          example: "What is digital twin simulation?"
        response:
          type: string
          description: The agent's response in this turn
          example: "Digital twin simulation is a virtual representation of a physical system..."
        timestamp:
          type: string
          description: ISO 8601 timestamp of this turn
          format: date-time
          example: "2025-12-21T01:00:00Z"

    SessionTerminationResponse:
      type: object
      required:
        - session_id
        - terminated_at
        - status
      properties:
        session_id:
          type: string
          description: Unique identifier for the terminated session
          example: "sess_abc123xyz"
        terminated_at:
          type: string
          description: ISO 8601 timestamp when session was terminated
          format: date-time
          example: "2025-12-21T02:00:00Z"
        status:
          type: string
          description: Status of the termination
          enum: [success, not_found, already_terminated]
          example: "success"

    HealthCheckResponse:
      type: object
      required:
        - status
        - timestamp
      properties:
        status:
          type: string
          description: Overall health status
          enum: [healthy, degraded, unhealthy]
          example: "healthy"
        timestamp:
          type: string
          description: ISO 8601 timestamp of the health check
          format: date-time
          example: "2025-12-21T01:00:00Z"
        services:
          type: object
          description: Health status of individual services
          properties:
            openai_api:
              type: string
              description: Status of OpenAI API connectivity
              enum: [available, unavailable]
              example: "available"
            qdrant_db:
              type: string
              description: Status of Qdrant database connectivity
              enum: [available, unavailable]
              example: "available"
            cohere_api:
              type: string
              description: Status of Cohere API connectivity
              enum: [available, unavailable]
              example: "available"
        metrics:
          type: object
          description: Performance metrics
          properties:
            avg_response_time:
              type: number
              description: Average response time in seconds
              example: 1.23
            active_sessions:
              type: integer
              description: Number of active agent sessions
              example: 15

    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error type identifier
          example: "invalid_query"
        message:
          type: string
          description: Human-readable error message
          example: "Query must be between 1 and 500 characters"
        details:
          type: object
          description: Additional error details (optional)
          example: {"field": "query", "value": ""}